#[display_name = "Dockerfile"]
#[path = "**/Dockerfile"]
pub fn dockerfile() {
    until /$/ {
        yield other;

        if /'/ {
            single_quote_string();
        } else if /"/ {
            until /$/ {
                yield string;
                if /\\./ {}
                else if /\$(?:\{[^}]+\}|[A-Za-z_]\w*)/ {
                    yield variable;
                }
                else if /"/ { yield string; break; }
                await input;
            }
        } else if /#.*/ {
            yield comment;
        } else if /\$(?:\{[^}]+\}|[A-Za-z_]\w*)/ {
            yield variable;
        } else if /(?:ADD|ARG|CMD|COPY|ENTRYPOINT|ENV|EXPOSE|FROM|HEALTHCHECK|LABEL|MAINTAINER|ONBUILD|RUN|SHELL|STOPSIGNAL|USER|VOLUME|WORKDIR)\>/ {
            yield keyword.other;
        } else if /\w+/ {
            // Gobble word chars to align the next iteration on a word boundary.
        }

        yield other;
    }
}
