#[display_name = "Dockerfile"]
#[path = "**/*Dockerfile*"]
pub fn dockerfile() {

        if /#.*/ {
            yield comment;
        } else if /'/ {
            until /$/ {
                yield string;
                if /\\./ {}
                else if /'/ { yield string; break; }
                await input;
            }
        } else if /"/ {
            until /$/ {
                yield string;
                if /\\./ {}
                else if /"/ { yield string; break; }
                await input;
            }
        } else if /(?:FROM|RUN|CMD|LABEL|MAINTAINER|EXPOSE|ENV|ADD|COPY|ENTRYPOINT|VOLUME|USER|WORKDIR|ARG|ONBUILD|STOPSIGNAL|HEALTHCHECK|SHELL)\>/ {
            yield keyword.other;
        } else if /\w+/ {
            // Gobble word chars to align the next iteration on a word boundary.
        }

        yield other;
}
