10 REM TEST
20 PRINT "A"
30 INPUT A
40 GOTO 40
50 END
60 *SUB
70 C=A*B
80 IF A>B THEN 80
90 IF NOT A AND B THEN 90
100 END PRINT INPUT DATA DIM READ LET RESTORE CLEAR WAIT DEF POKE OUT LPRINT WIDTH SWAP ERASE DEFSTR DEFINT DEFSNG DEFDBL LINE WRITE PLAY SOUND COMMON CHAIN OPTION BASE
105 RANDOMIZE OPEN FIELD GET PUT CLOSE LSET RSET COLOR CIRCLE CLS PSET PRESET PAINT SCREEN LOCATE BEEP PEN
110 TAB SPC ERL ERR STRING$ USING INSTR VARPTR INKEY$ LEFT$ RIGHT$ MID$ SGN INT ABS SQR RND SIN LOG EXP COS TAN ATN FRE INP POS LEN STR$ VAL ASC
115 CHR$ PEEK SPACE$ OCT$ HEX$ LPOS CINT CSNG CDBL FIX CVI CVS CVD EOF LOC LOF  MKI$ MKS$ MKD$ CSRLIN DATE$ 
120 RUN NEW TRON TROFF FILES NAME KILL BLOAD BSAVE COM KEY STICK STRIG VIEW WINDOW POINT TIME$ ON STOP
150 CONSOLE BGM DSKO$ ROLL HELP PALET TALK KANJI  CMD SET MERGE STATUS SEARCH MAP DSKF FPOS USR FN ATTR$  XOR EQV
155 IMP LIST CONT LLIST EDIT MENU DELETE AUTO RENUM CLOAD CSAVE LOAD SAVE LFILES MON COPY TERM MOTOR PAD GRP$ OFF 
160 AND OR MOD  NOT
