10 REM TEST
11 REM
12 REM--
13 REMARK
17 'TEST
19 '
20 PRINT "A"
30 INPUT A
40 GOTO 40
50 B=3.1415:B=.1415:B=3.1415E+2:B=.1415E2:B=3.1415E-2:B=3.1415D+2:B=.1415D2:B=3.1415D-2:B=&H5C66:B=&o1234
60 *SUB
70 C=A*B
80 IF A>B THEN 80
90 IF NOT A AND B THEN 90
91 DATA 3.1415
92 DATA"DATA"
93 DATADATA
94 DATA
100 REM GitHub-recognized keywords (controls and operators)
102 ELSE FOR GOSUB GOTO IF NEXT RETURN THEN TO
103 AND MOD NOT OR
105 REM GitHub-recognized keywords (general)
110 ABS AS ASC ATN BASE BEEP BLOAD BSAVE CALL CDBL CHAIN CHR$ CINT CIRCLE CLEAR 
120 CLOSE CLS COLOR COM COMMON COS CSNG CSRLIN CVD CVI CVS DATA 
130 DATE$ DEF DEFDBL DEFINT DEFSNG DEFSTR DIM END EOF ERASE ERL ERR ERROR EXP FIELD 
140 FILES FIX FRE GET HEX$ INKEY$ INP INPUT INSTR INT KEY KILL LEFT$ LEN LET 
150 LINE LOC LOCATE LOF LOG LPOS LPRINT LSET MID$ MKD$ MKI$ MKS$ NAME NEW OCT$ ON 
160 OPEN OPTION OUT PAINT PEEK PEN PLAY POINT POKE POS PRESET PRINT PSET PUT 
170 RANDOMIZE READ RESTORE RESUME RIGHT$ RND RSET RUN SCREEN SGN SIN SOUND 
180 SPACE$ SPC SQR STICK STOP STR$ STRIG STRING$ SWAP SYSTEM TAB TAN TIME$ TROFF TRON 
190 USING VAL VARPTR VIEW WAIT WEND WHILE WIDTH WINDOW WRITE
195 REM GitHub-unrecognized keywords (approved)
200 AUTO CLOAD CMD CONSOLE CONT CSAVE DELETE DSKF DSKO$ EDIT EQV EXEC 
220 HELP IMP INTERVAL KANJI LFILES LIST LLIST LOAD LOADM MAP 
230 MON MOTOR OFF RENUM SAVE SAVEM SEGPTR STEP TALK TERM USR XOR
250 REM GitHub-unrecognized keywords (suspended)
260 ANPORT ATTR$ BGM BUBINI BUBR BUBW CHILD COPY DSKINI FN FPOS GCURSOR GRP$ HARDC
270 MENU MERGE MOUSE PAD PALET ROLL SEARCH  SET STATUS UNLIST
