10 REM TEST
20 PRINT "A"
30 INPUT A
40 GOTO 40
50 END
60 *SUB
70 C=A*B
80 IF A>B THEN 80
90 IF NOT A AND B THEN 90
100 REM controls and operators
102 AND ELSE FOR GOSUB GOTO IF MOD NEXT NOT OR RETURN THEN TO
105 REM statements, commands and functions
110 ABS ASC ATN BASE BEEP BLOAD BSAVE CALL CDBL CHAIN CHR$ CINT CIRCLE CLEAR 
120 CLOSE CLS COLOR COM COMMON COS CSNG CSRLIN CVD CVI CVS DATA DATE$ DEF 
130 DEFDBL DEFINT DEFSNG DEFSTR DIM END EOF ERASE ERL ERR ERROR EXP FIELD 
140 FILES FIX FRE GET HEX$ INKEY$ INP INPUT INSTR INT KEY KILL LEFT$ LEN LET 
150 LINE LOC LOCATE LOF LOG LPOS LPRINT LSET MID$ MKD$ MKI$ MKS$ NAME NEW OCT$ ON 
160 OPEN OPTION OUT PAINT PEEK PEN PLAY POINT POKE POS PRESET PRINT PSET PUT 
170 RANDOMIZE READ RESTORE RESUME RIGHT$ RND RSET RUN SCREEN SGN SIN SOUND 
180 SPACE$ SPC SQR STICK STOP STR$ STRIG STRING$ SWAP TAB TAN TIME$ TROFF TRON 
190 USING VAL VARPTR VIEW WAIT WEND WHILE WIDTH WINDOW WRITE
195 REM unrecognized
200 ATTR$ AUTO BGM CLOAD CMD CONSOLE CONT COPY CSAVE DELETE DSKF DSKO$ EDIT 
210 EQV EXEC FN FPOS GRP$ HELP IMP KANJI LFILES LIST LLIST LOAD MAP MAP MENU 
220 MERGE MON MOTOR OFF PAD PALET RENUM ROLL SAVE SEARCH SEARCH SET STATUS 
230 STEP TALK TERM USR XOR
240 REM unknown
250 CURSOR SYMBOL CONNECT
